### PR TITLE
Example codes for various dgraph clients

### PR DESCRIPTION
**Pull request by prashant-shahi**
- [x] example code for Python client
- [x] example code for JavaScript (gRPC and HTTP) clients
- [x] example code for Java client

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/hugo-docs/29)

### CODE REVIEW

**Review by danielmai — CHANGES_REQUESTED** [review]
Nice work adding examples for Python and JavaScript, including generating example code for both `query` and `queryWithVars` :thumbsup: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/hugo-docs/29#-:-LmmW7Gu-lTmKV5X9ewF:b-kinzdv)* status: all files reviewed, 5 unresolved discussions (waiting on @prashant-shahi)

___
*[layouts/partials/example-js-grpc.html, line 12 at r1](https://reviewable.io/reviews/dgraph-io/hugo-docs/29#-LmmTdMn1IpXFFOhDdkG:-LmmTdMn1IpXFFOhDdkH:bjet1d7) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/9bbe2defbf7a20d6c61c5d90aadf75457edc4ab1/layouts/partials/example-js-grpc.html#L12)):*
> ```HTML
> const grpc = require("grpc");
> 
> const DGRAPH = process.env.DGRAPH || "localhost:9080";
> ```

Like the Go example code, we can simply put "localhost:9080" into the DgraphClientStub argument instead of picking up the value from an environment variable.
___
*[layouts/partials/example-js-http.html, line 11 at r1](https://reviewable.io/reviews/dgraph-io/hugo-docs/29#-LmmTrcFCiwgjR9Rvc1W:-LmmTrcG64_36jgn_CkA:byui26k) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/9bbe2defbf7a20d6c61c5d90aadf75457edc4ab1/layouts/partials/example-js-http.html#L11)):*
> ```HTML
> <pre><code class="no-copy" tabindex="-1">const dgraph = require("dgraph-js-http");
> 
> const DGRAPH = process.env.DGRAPH || "http://localhost:8080";
> ```

Like the Go example code, we can simply put "localhost:8080" into the DgraphClientStub argument instead of picking up the value from an environment variable.
___
*[layouts/partials/example-python.html, line 13 at r1](https://reviewable.io/reviews/dgraph-io/hugo-docs/29#-LmmTvj92UowYJ0TVJ3b:-LmmTvj92UowYJ0TVJ3c:bjet1d7) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/9bbe2defbf7a20d6c61c5d90aadf75457edc4ab1/layouts/partials/example-python.html#L13)):*
> ```HTML
> import json
> 
> DGRAPH = os.getenv('DGRAPH', 'localhost:9080')
> ```

Like the Go example code, we can simply put "localhost:9080" into the DgraphClientStub argument instead of picking up the value from an environment variable.
___
*[layouts/partials/example-python.html, line 26 at r1](https://reviewable.io/reviews/dgraph-io/hugo-docs/29#-LmmU1RB3YUSduocFqt7:-LmmU1RB3YUSduocFqt8:b-rw205d) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/9bbe2defbf7a20d6c61c5d90aadf75457edc4ab1/layouts/partials/example-python.html#L26)):*
> ```HTML
> {{ end }}
> 
>     print('Response: ', json.loads(res.json))
> ```

This prints out a two-element tuple with `'Response: '` as the first element and a Python dict as the second element. Let's properly print a string with the JSON response as-is it its JSON string form.

```
print('Response: {}'.format(res.json))
```
___
*[layouts/shortcodes/runnable.html, line 20 at r1](https://reviewable.io/reviews/dgraph-io/hugo-docs/29#-LmmVu6NAhB79Sv3Hm1L:-LmmVu6NAhB79Sv3Hm1M:bgyitaz) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/9bbe2defbf7a20d6c61c5d90aadf75457edc4ab1/layouts/shortcodes/runnable.html#L20)):*
> ```
>                     <a class="language" data-action="nav-lang" data-target="js-grpc" href="#">JS (gRPC)</a>
>                     <a class="language" data-action="nav-lang" data-target="js-http" href="#">JS (HTTP)</a>
> ```

Call these "JavaScript (gRPC)" and "JavaScript (HTTP)"

**Comment by danielmai** [comment]
___
*[layouts/partials/example-python.html, line 26 at r1](https://reviewable.io/reviews/dgraph-io/hugo-docs/29#-LmmU1RB3YUSduocFqt7:-LmmWQe-BRWnOCN7Mz9Z:b-49wmig) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/9bbe2defbf7a20d6c61c5d90aadf75457edc4ab1/layouts/partials/example-python.html#L26)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

This prints out a two-element tuple with `'Response: '` as the first element and a Python dict as the second element. Let's properly print a string with the JSON response as-is it its JSON string form.

```
print('Response: {}'.format(res.json))
```
</blockquote></details>

in* its

**Review by prashant-shahi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/hugo-docs/29)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @danielmai and @prashant-shahi)

___
*[layouts/partials/example-python.html, line 26 at r1](https://reviewable.io/reviews/dgraph-io/hugo-docs/29#-LmmU1RB3YUSduocFqt7:-LmnbMK2AKb_mirWTSTQ:b-33kfdo) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/9bbe2defbf7a20d6c61c5d90aadf75457edc4ab1/layouts/partials/example-python.html#L26)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

in* its
</blockquote></details>

Using the above snippet is printing the byte string (`b'` prefixed string) instead of a string.

Using `JSON.loads` along with your suggested snippet is printing the JSON string and with some proper spacing as well.
```python
print('Response: {}'.format(json.loads(res.json)))
```

Let me know if I need to modify anything from this.

**Review by prashant-shahi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/hugo-docs/29)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @danielmai)

___
*[layouts/partials/example-js-grpc.html, line 12 at r1](https://reviewable.io/reviews/dgraph-io/hugo-docs/29#-LmmTdMn1IpXFFOhDdkG:-Lmnf3R29Z18PqEH5s_F:b-896fix) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/9bbe2defbf7a20d6c61c5d90aadf75457edc4ab1/layouts/partials/example-js-grpc.html#L12)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

Like the Go example code, we can simply put "localhost:9080" into the DgraphClientStub argument instead of picking up the value from an environment variable.
</blockquote></details>

Done.
___
*[layouts/partials/example-js-http.html, line 11 at r1](https://reviewable.io/reviews/dgraph-io/hugo-docs/29#-LmmTrcFCiwgjR9Rvc1W:-Lmnf2rr-E_3WGRsraVx:b-896fix) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/9bbe2defbf7a20d6c61c5d90aadf75457edc4ab1/layouts/partials/example-js-http.html#L11)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

Like the Go example code, we can simply put "localhost:8080" into the DgraphClientStub argument instead of picking up the value from an environment variable.
</blockquote></details>

Done.
___
*[layouts/partials/example-python.html, line 13 at r1](https://reviewable.io/reviews/dgraph-io/hugo-docs/29#-LmmTvj92UowYJ0TVJ3b:-Lmnf-NKDLHNlJ-sn9NY:b-896fix) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/9bbe2defbf7a20d6c61c5d90aadf75457edc4ab1/layouts/partials/example-python.html#L13)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

Like the Go example code, we can simply put "localhost:9080" into the DgraphClientStub argument instead of picking up the value from an environment variable.
</blockquote></details>

Done.
___
*[layouts/shortcodes/runnable.html, line 20 at r1](https://reviewable.io/reviews/dgraph-io/hugo-docs/29#-LmmVu6NAhB79Sv3Hm1L:-Lmnf2BQ6VWSUXoTt0uq:b-896fix) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/9bbe2defbf7a20d6c61c5d90aadf75457edc4ab1/layouts/shortcodes/runnable.html#L20)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
>                     <a class="language" data-action="nav-lang" data-target="js-grpc" href="#">JS (gRPC)</a>
>                     <a class="language" data-action="nav-lang" data-target="js-http" href="#">JS (HTTP)</a>
> ```

Call these "JavaScript (gRPC)" and "JavaScript (HTTP)"

</blockquote></details>

Done.

**Review by danielmai — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/hugo-docs/29)* status: all files reviewed, 3 unresolved discussions (waiting on @prashant-shahi)

___
*[layouts/partials/example-python.html, line 26 at r1](https://reviewable.io/reviews/dgraph-io/hugo-docs/29#-LmmU1RB3YUSduocFqt7:-LmuHegL3plH71cf5nMQ:b-vkf2q2) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/9bbe2defbf7a20d6c61c5d90aadf75457edc4ab1/layouts/partials/example-python.html#L26)):*
Good catch. Let's do a similar decoding like you did in the Java example code so that the response is valid JSON with double-quoted keys and values.

```
>>> print('Response: {}'.format(json.loads(res.json)))
Response: {'bladerunner': [{'uid': '0x1228de', 'name@en': 'Blade Runner', 'initial_release_date': '1982-06-25T00:00:00Z', 'netflix_id': '70083726'}]}
```

Suggested change:
```
>>> print('Response: {}'.format(res.json.decode('utf-8')))
Response: {"bladerunner":[{"uid":"0x1228de","name@en":"Blade Runner","initial_release_date":"1982-06-25T00:00:00Z","netflix_id":"70083726"}]}
```
___
*[layouts/shortcodes/runnable.html, line 22 at r2](https://reviewable.io/reviews/dgraph-io/hugo-docs/29#-Lmu7sPeCeYgA-33XgEy:-Lmu7sPeCeYgA-33XgEz:baynqta) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/d4a194d350219b87cfe26e813e95a85b5df18225/layouts/shortcodes/runnable.html#L22)):*
> ```HTML
>                     <a class="language" data-action="nav-lang" data-target="js-grpc" href="#">JavaScript (gRPC)</a>
>                     <a class="language" data-action="nav-lang" data-target="js-http" href="#">JavaScript (HTTP)</a>
>                     <a class="language" data-action="nav-lang" data-target="java" href="#">Java</a>
> ```

Move Java next to Go. It's probably our most popular client aside from Go. The order should be: Go, Java, Python, JavaScript (gRPC), JavaScript (HTTP), Curl.
___
*[layouts/shortcodes/runnable.html, line 79 at r2](https://reviewable.io/reviews/dgraph-io/hugo-docs/29#-Lmu7q9gEn9iwuYFQEXZ:-Lmu7q9h1fPOIT5ZCKOK:b-jkuyij) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/d4a194d350219b87cfe26e813e95a85b5df18225/layouts/shortcodes/runnable.html#L79)):*
> ```HTML
>             <div class="runnable-tab-content" data-tab="java">
>               {{/*
>                 TODO: Currently uncommented snippet will work but if any editing done on the query, it doesn't appear in Java example code.
> ```

Why does this happen?

**Review by danielmai — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/hugo-docs/29#-:-LnDYVpjAtwffY80TQDp:bnfp4nl)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @danielmai and @prashant-shahi)

**Pull request merged**
