### PR TITLE
Added Content-Type header for v1.1

### PR DESCRIPTION
**Pull request by prashant-shahi**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/hugo-docs/26)

### CODE REVIEW

**Comment by danielmai** [comment]
Does this change the example output for the `Curl` tab in all the runnables? It should include the right header that can be copied.

**Comment by prashant-shahi** [comment]
@danielmai  Now it does.

**Review by mangalaman93 — CHANGES_REQUESTED** [review]
Please search through the whole repo to find list of headers that are still getting used. From the PR https://github.com/dgraph-io/dgraph/pull/3637 and https://github.com/dgraph-io/dgraph/pull/3365, we have removed following headers -
  * X-Dgraph-IgnoreIndexConflict
  * X-Dgraph-MutationType
  * X-Dgraph-CommitNow
  * X-Dgraph-Vars

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/hugo-docs/26#-:-LmiWO509noj2QTXvAfs:bpotdqb)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @danielmai, @paulftw, @pawanrawal, and @prashant-shahi)

___
*[layouts/shortcodes/runnable.html, line 53 at r2](https://reviewable.io/reviews/dgraph-io/hugo-docs/26#-LmiWLQO3D-u3iaCSh4g:-LmiWLQO3D-u3iaCSh4h:b86lx5t) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/5e63a8da59124e35cb2687f9f7cda51e7aa4ef2a/layouts/shortcodes/runnable.html#L53)):*
> ```HTML
> 
>             <div class="runnable-tab-content" data-tab="curl">
>               <pre><code class="no-copy" tabindex="-1">curl -H "Content-Type: application/graphql+-" localhost:8080/query -XPOST {{ with .Get "vars" }}-H 'X-Dgraph-Vars: {{.}}' {{ end }}-d '<br/><span class="query-content">{{ $code }}</span>' | python -m json.tool | less
> ```

We do not support `X-Dgraph-vars` in 1.1. We should remove it
___
*[static/js/runnable.js, line 341 at r2](https://reviewable.io/reviews/dgraph-io/hugo-docs/26#-LmiWMUIEci2RV8OyRLf:-LmiWMUIEci2RV8OyRLg:b-5h08ck) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/5e63a8da59124e35cb2687f9f7cda51e7aa4ef2a/static/js/runnable.js#L341)):*
> ```JavaScript
>     $.post({
>       url: window.DGRAPH_ENDPOINT,
>       headers: { "X-Dgraph-Vars": vars, "Content-Type": "application/graphql+-"},
> ```

same here!

**Review by prashant-shahi — COMMENTED** [review]
Removing vars will affect the code examples using *vars*.  Like here : https://docs.dgraph.io/query-language/#graphql-variables

Please let me know what would be the appropriate thing to do here.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/hugo-docs/26#-:-LmkWERl9XCysvE4v0i5:bgd4z1u)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @danielmai, @paulftw, @pawanrawal, and @prashant-shahi)

**Review by danielmai — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/hugo-docs/26)* status: all files reviewed, 1 unresolved discussion (waiting on @prashant-shahi)

___
*[layouts/shortcodes/runnable.html, line 57 at r3](https://reviewable.io/reviews/dgraph-io/hugo-docs/26#-Ln-IGE64S24UnIYChM6:-Ln-IGE64S24UnIYChM7:b-wrk934) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/a0d3931e805bda4d44305e0daf487e241c41a2a6/layouts/shortcodes/runnable.html#L57)):*
> ```HTML
>                 </code></pre>
>             {{ else }}
>               <pre><code class="no-copy" tabindex="-1">curl -H "Content-Type: application/json" localhost:8080/query -XPOST -d '{ <br/>"query": "<span class="curl-query">{{ $code }}</span>",<br/>"variables": {{ .Get "vars" }}<br/>}' | python -m json.tool | less
> ```

Is there a way to set GraphQL Variables with `Content-Type: application/graphql+-`? I thought that was possible.

**Review by mangalaman93 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/hugo-docs/26)* status: all files reviewed, 1 unresolved discussion (waiting on @danielmai)

___
*[layouts/shortcodes/runnable.html, line 57 at r3](https://reviewable.io/reviews/dgraph-io/hugo-docs/26#-Ln-IGE64S24UnIYChM6:-Ln1bmQg3vLRM_ZUHu0E:bfxshys) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/a0d3931e805bda4d44305e0daf487e241c41a2a6/layouts/shortcodes/runnable.html#L57)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

Is there a way to set GraphQL Variables with `Content-Type: application/graphql+-`? I thought that was possible.
</blockquote></details>

Nope! Only application/json supports variables.

**Review by danielmai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/hugo-docs/26)* status: all files reviewed, 1 unresolved discussion (waiting on @prashant-shahi)

___
*[layouts/shortcodes/runnable.html, line 54 at r3](https://reviewable.io/reviews/dgraph-io/hugo-docs/26#-LnD_xHtCODX1Pm4R3y_:-LnD_xHtCODX1Pm4R3ya:b-ep597u) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/a0d3931e805bda4d44305e0daf487e241c41a2a6/layouts/shortcodes/runnable.html#L54)):*
> ```HTML
>             <div class="runnable-tab-content" data-tab="curl">
>             {{ if eq (.Get "vars") nil }}
>               <pre><code class="no-copy" tabindex="-1">curl -H "Content-Type: application/graphql+-" localhost:8080/query -XPOST -d '<br/><span class="query-content">{{ $code }}</span>' | python -m json.tool | less
> ```

Another thing: Showing the `Content-Type` should be versioned so that the correct curl command is shown for v1.0.x docs. Take a look at how the Go code example template checks for versioning to do something similar for curl.
___
*[layouts/shortcodes/runnable.html, line 57 at r3](https://reviewable.io/reviews/dgraph-io/hugo-docs/26#-Ln-IGE64S24UnIYChM6:-LnD_oFN--waZJ6v9pZr:bmxmivf) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/a0d3931e805bda4d44305e0daf487e241c41a2a6/layouts/shortcodes/runnable.html#L57)):*
<details><summary><i>Previously, mangalaman93 (Aman Mangal) wrote…</i></summary><blockquote>

Nope! Only application/json supports variables.
</blockquote></details>

OK, interesting.

**Review by prashant-shahi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/hugo-docs/26)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @danielmai)

___
*[layouts/shortcodes/runnable.html, line 54 at r3](https://reviewable.io/reviews/dgraph-io/hugo-docs/26#-LnD_xHtCODX1Pm4R3y_:-LnIVoPn8LmpIYqhyYLh:b-896fix) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/a0d3931e805bda4d44305e0daf487e241c41a2a6/layouts/shortcodes/runnable.html#L54)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

Another thing: Showing the `Content-Type` should be versioned so that the correct curl command is shown for v1.0.x docs. Take a look at how the Go code example template checks for versioning to do something similar for curl.
</blockquote></details>

Done.

**Review by danielmai — APPROVED** [review]
One comment, and then :lgtm:.

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/hugo-docs/26#-:-LnJoWc23YgzLsCQAGld:b-2uqr1g)* status: all files reviewed, 2 unresolved discussions (waiting on @danielmai and @prashant-shahi)

___
*[layouts/partials/example-curl.html, line 9 at r4](https://reviewable.io/reviews/dgraph-io/hugo-docs/26#-LnJoNSEES3xBvAx5YsU:-LnJoNSEES3xBvAx5YsV:blyrlqc) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/22afe8feeae5f6a4e661cd708b2dcbf7fae33de6/layouts/partials/example-curl.html#L9)):*
> ```
> {{ $versionGe105 := or (eq $currentBranch "master") (gt $majorVersion 1) (and (eq $majorVersion 1) (gt $minorVersion 0)) (and (eq $majorVersion 1) (eq $minorVersion 0) (ge $patchVersion 5)) }}
> {{ $versionGe11 := or (eq $currentBranch "master") (gt $majorVersion 1) (and (eq $majorVersion 1) (gt $minorVersion 1)) }}
> ```
Should both `versionGe105` and `versionGe11` contain checks for `master`?

Other than that, LGTM to merge.

**Review by prashant-shahi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/hugo-docs/26)* status: all files reviewed, 2 unresolved discussions (waiting on @danielmai)

___
*[layouts/partials/example-curl.html, line 9 at r4](https://reviewable.io/reviews/dgraph-io/hugo-docs/26#-LnJoNSEES3xBvAx5YsU:-LnMTWcH2LyPJvo59HE7:b-s5x6cv) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/22afe8feeae5f6a4e661cd708b2dcbf7fae33de6/layouts/partials/example-curl.html#L9)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> {{ $versionGe105 := or (eq $currentBranch "master") (gt $majorVersion 1) (and (eq $majorVersion 1) (gt $minorVersion 0)) (and (eq $majorVersion 1) (eq $minorVersion 0) (ge $patchVersion 5)) }}
> {{ $versionGe11 := or (eq $currentBranch "master") (gt $majorVersion 1) (and (eq $majorVersion 1) (gt $minorVersion 1)) }}
> ```
Should both `versionGe105` and `versionGe11` contain checks for `master`?

Other than that, LGTM to merge.
</blockquote></details>

`versionGe105` was helpful for go example, which I believe was after **dgo** client was introduced.
Removing `versionGe105` check from the curl example.

**Pull request merged**
