### PR TITLE
Fixes for broken links for latest docs and black dgraph logo

### PR DESCRIPTION
**Pull request by prashant-shahi**
Signed-off-by: Prashant Shahi <prashant@dgraph.io>

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/hugo-docs/51)

### CODE REVIEW

**Review by danielmai — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/hugo-docs/51)* status: all files reviewed, 2 unresolved discussions (waiting on @lgalatin, @prashant-shahi, and @vvbalaji-dgraph)

___
*[layouts/_default/article.html, line 8 at r1](https://reviewable.io/reviews/dgraph-io/hugo-docs/51#-M7LcL5CCJayOFG78qXb:-M7LcL5CCJayOFG78qXc:bl4qzna) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/dc77f7869eef041c03fc095958f2ccc97cd26433/layouts/_default/article.html#L8)):*
> ```HTML
> {{ if (eq $currentVersion "master") }}
>   <div class="alert alert-warning">
>     <i class="fa fa-warning"></i> You are looking at the docs for the unreleased <code>master</code> branch of Dgraph. The latest version is <a href="{{ .Site.BaseURL }}/..">{{ $latestVersion }}</a>.
> ```

.Site.BaseURL is currently `https://dgraph.io/docs`. So, `/..` would go to `https://dgraph.io`? That seems wrong?
___
*[layouts/shortcodes/runnable.html, line 102 at r1](https://reviewable.io/reviews/dgraph-io/hugo-docs/51#-M7Lc_f85W_aEqUN-Vab:-M7Lc_f85W_aEqUN-Vac:bp0nyy9) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/dc77f7869eef041c03fc095958f2ccc97cd26433/layouts/shortcodes/runnable.html#L102)):*
> ```
> }}/images/dgraph-black.png')
> ```
Is the black logo gone on the current site?

**Review by prashant-shahi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/hugo-docs/51)* status: all files reviewed, 2 unresolved discussions (waiting on @danielmai, @lgalatin, and @vvbalaji-dgraph)

___
*[layouts/_default/article.html, line 8 at r1](https://reviewable.io/reviews/dgraph-io/hugo-docs/51#-M7LcL5CCJayOFG78qXb:-M7Mhp5WEdSOnEIOQBbB:bgie33x) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/dc77f7869eef041c03fc095958f2ccc97cd26433/layouts/_default/article.html#L8)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

.Site.BaseURL is currently `https://dgraph.io/docs`. So, `/..` would go to `https://dgraph.io`? That seems wrong?
</blockquote></details>

These divs within `if block` is shown only for builds with non-latest versions i.e. `/docs/master` and `/docs/<version>` baseURLs.

**Preview link**: https://dgraph-wiki-test.surge.sh/docs/

_Note: v1.0.X and v1.1.X versions of docs are not included here because of **Surge.sh** limits of 430MB or 4500 files._
___
*[layouts/shortcodes/runnable.html, line 102 at r1](https://reviewable.io/reviews/dgraph-io/hugo-docs/51#-M7Lc_f85W_aEqUN-Vab:-M7MjWKu78bhxqzebQGo:b-gnixxv) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/dc77f7869eef041c03fc095958f2ccc97cd26433/layouts/shortcodes/runnable.html#L102)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> }}/images/dgraph-black.png')
> ```
Is the black logo gone on the current site?
</blockquote></details>

Yes, the black logo is missing from the runnable blocks in [dgraph.io/docs/query-language](https://dgraph.io/docs/query-language).

**Preview**: https://dgraph-wiki-test.surge.sh/docs/query-language/

**Review by danielmai — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/hugo-docs/51#-:-M7OXX2F1u416y09q_A2:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @lgalatin, @prashant-shahi, and @vvbalaji-dgraph)

___
*[layouts/_default/article.html, line 8 at r1](https://reviewable.io/reviews/dgraph-io/hugo-docs/51#-M7LcL5CCJayOFG78qXb:-M7OXNsZ8-rPTVSRLVC3:b-9cxu84) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/dc77f7869eef041c03fc095958f2ccc97cd26433/layouts/_default/article.html#L8)):*
<details><summary><i>Previously, prashant-shahi (Prashant Shahi) wrote…</i></summary><blockquote>

These divs within `if block` is shown only for builds with non-latest versions i.e. `/docs/master` and `/docs/<version>` baseURLs.

**Preview link**: https://dgraph-wiki-test.surge.sh/docs/

_Note: v1.0.X and v1.1.X versions of docs are not included here because of **Surge.sh** limits of 430MB or 4500 files._
</blockquote></details>

Great, thanks for clarifying.
___
*[layouts/shortcodes/runnable.html, line 102 at r1](https://reviewable.io/reviews/dgraph-io/hugo-docs/51#-M7Lc_f85W_aEqUN-Vab:-M7OWra9CMYzbFFASiWV:b-gqx3ku) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/dc77f7869eef041c03fc095958f2ccc97cd26433/layouts/shortcodes/runnable.html#L102)):*
<details><summary><i>Previously, prashant-shahi (Prashant Shahi) wrote…</i></summary><blockquote>

Yes, the black logo is missing from the runnable blocks in [dgraph.io/docs/query-language](https://dgraph.io/docs/query-language).

**Preview**: https://dgraph-wiki-test.surge.sh/docs/query-language/
</blockquote></details>

Ah, it's missing in the surge preview, not the official docs. Thanks.

**Review by prashant-shahi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/hugo-docs/51)* status: all files reviewed, 1 unresolved discussion (waiting on @danielmai, @lgalatin, and @vvbalaji-dgraph)

___
*[layouts/shortcodes/runnable.html, line 102 at r1](https://reviewable.io/reviews/dgraph-io/hugo-docs/51#-M7Lc_f85W_aEqUN-Vab:-M7PCfRt4s5PEWjlEmkl:bxfhthf) ([raw file](https://github.com/dgraph-io/hugo-docs/blob/dc77f7869eef041c03fc095958f2ccc97cd26433/layouts/shortcodes/runnable.html#L102)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

Ah, it's missing in the surge preview, not the official docs. Thanks.
</blockquote></details>

Oh, my bad. I meant for the non-latest versions as you can see in the comparison below:

1: https://dgraph.io/docs/master/query-language/
2: https://dgraph-wiki-test.surge.sh/docs/master/query-language/

**Pull request merged**
